import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ['200', '300', '500', '700', '900']
});

const metadata: Metadata = {
  title: "CryptoCap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-full w-full bg-deepblue px-6 sm:px-14 ${poppins.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
